BAN-L0004: Added Link Component
apyrophob/banany pull request #8
Opened 2020-10-20 10:04 UTC by apyrophob

2020-10-20 17:50 UTC, likemoody commented on src/components/Link/Link.js
> +        <link className='link' href={linkHref} />
Let's use tag `<a>`. `<link>` is for something else.

2020-10-20 17:50 UTC, likemoody commented on src/components/Link/Link.js
> +LinkComponent.defautProps = {
Let's remove default props. // remid to talk about that.

2020-10-20 19:58 UTC, apyrophob commented on src/components/Link/Link.js
> +        <link className='link' href={linkHref} />
We can also use <Link /> component from React.

2020-10-21 15:32 UTC, likemoody commented on src/components/Link/Link.js
> +        <a className='link' href={linkHref}></a>
Link has to have title, add `linkTitle` prop here.

2020-10-21 15:33 UTC, likemoody commented on src/components/Link/Link.js
> +        <link className='link' href={linkHref} />
Indeed, but we can't use component in itself yet.

2020-10-22 11:25 UTC, likemoody requested changes

2020-10-22 11:25 UTC, likemoody commented on src/components/Image/Image.js
> -ImageComponent.PropTypes = {
Warum? (Why?)

2020-10-22 11:25 UTC, likemoody commented on src/components/Link/Link.js
> -        <a className='link' href={linkHref}></a>
Do not forget indentation.

2020-10-22 11:26 UTC, likemoody requested changes

2020-10-22 11:26 UTC, likemoody commented on src/components/Link/Link.js
> +    <a className='link' href={linkHref}>{linkTitle}</a>
Do not forget indentation.

2020-10-22 11:27 UTC, likemoody commented on src/components/Image/Image.js
> +ImageComponent.propTypes = {
Warum? (Why?)

2020-10-22 22:39 UTC, apyrophob commented on src/components/Image/Image.js
> +ImageComponent.propTypes = {
It works in that way, if you type .PropTypes(not .propTypes) it will not work.

2020-10-23 10:05 UTC, likemoody commented
OK, let's merge

2020-10-23 11:10 UTC, merged